# Generated by Django 3.1.2 on 2023-06-22 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20230622_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fecha_germ',
            field=models.DateField(blank=True),
        ),
    ]
