# Generated by Django 3.1.2 on 2023-06-23 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20230622_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fecha_germ',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
