# Generated by Django 3.1.2 on 2023-06-23 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20230622_2039'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacto',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
